### PR TITLE
Should not run out of memory on large uploads now

### PR DESCRIPTION
**Pull request by OhioVR**
Uploads would always make it to the server but during the processing step a temp file was being created that is essentially a copy of the upload. During the copy procedure it would load the entire file into system ram and then dump it out. So if you had something like a full length bluray film an ordinary VPS would choke on the file. The solution was to create a symlink for the already uploaded file with the proper file name so that the rest of the program could proceed with encoding and still generation. Earlier I posted this solution but I had neglected to test it with the bulk upload feature. Now that it has been tested and fixed I've submitted this new pull request that should work for all three upload types. 

I've never contributed to open source before so I didn't know how to merge upstream changes, that is why the previous pull request failed. Everything should be fine now. I've also cleaned up my source to match what it is going into. I had a auto formatter that was making it look like the main Encoder.php file had hundreds of changes when it really only has changes in a few areas.

### CODE REVIEW

**Comment by DanielnetoDotCom** [comment]
Are you sure you fixed the conflict on Encoder.php?

looks like you merge the files, not resolve the conflict

**Comment by OhioVR** [comment]
I was having some problems with getting the upstream changs merged. I've not had any experience with it before. I clicked on "uploads no restricted by memory" above and it doesn't show your file, just my side so I'm not sure what I did wrong. There should have been only one commit but I wasn't sure what I was doing. What I did was commit each time I thought I had the upstream changes merged and failed several times. But the last time did work. Sorry about this I'm not too good with git at the moment. What I could do is try to do some fork surgury or delete the fork and refork it and try to transplant my changed files. What I did to try to merge the encoder.php file to yours was to use an online diff tool to compare yours to my version and eliminate as many superficial differences that there were (like placement of curly braces). After pulling upstream changes I retested it.

**Comment by OhioVR** [comment]
I'm going to try closing this request, removing my old pull request, reforking, merging my changes, and then trying again. Thanks for your patientence on this.

**Comment by DanielnetoDotCom** [comment]
No problem , I went to the same problem at the begin.

when there is a conflict you have to manually resolve it, creating a new file based on the 2 conflicted version files.

there is no automatic solution for conflicts

**Pull request closed without merging**
