### PR TITLE
uploads not restricted by memory

### PR DESCRIPTION
**Pull request by OhioVR**
Hi Daniel,
Let me know if this pull request is free of conflicts. I saw there was some garbage in my previous pull request. Thanks for your patience.

### CODE REVIEW

**Comment by DanielnetoDotCom** [comment]
Question...

Why did you change the GIF FFMPEG generator to:

`$ffmpeg ="ffmpeg -ss {$duration} -t {$howLong} -i {$pathFileName} -i {$pathFileName}palette.png -filter_complex \"fps=10,scale=(iw*sar)*min(320/(iw*sar)\,180/ih):ih*min(320/(iw*sar)\,180/ih):flags=lanczos[x];[x][1:v]paletteuse, pad=320:180:(320-iw*min(320/iw\,180/ih))/2:(180-ih*min(320/iw\,180/ih))/2\" {$destinationFile}";`

Looks like the colors have a worst quality now

**Comment by OhioVR** [comment]
Hi Daniel,

If you see the comment it mentions that I was trying to make portrait video thumbnails look a little better and have them letterboxed:

            // I've discovered that if the ss parameter comes before the input flag, a tremendous time penalty is avoided.
            // Also I've developed this ffmpeg line to allow unusual aspect videos to be letter boxed
            // so that they don't get rendered incorrectly on the youphptube site. https://superuser.com/a/891478

I wonder if I may have changed this line (the pallet generator) while trying to figure out how it works:

$ffmpeg ="ffmpeg -y -ss {$duration} -t {$howLong} -i {$pathFileName} -vf fps=10,scale=320:-1:flags=lanczos,palettegen {$pathFileName}palette.png";'

now that I think about it shouldn't the scale be:

320:-2

instead of 

320:-1

have a look at the pallet file and see if it is large enough..

**Comment by OhioVR** [comment]
I tried encoding with both scale options for the pallet and it looks the same really. 
originalgif

newgif

I think both look pretty good considering they can only have 256 colors across multiple frames. What quality issues do you see in yours? Like banding or dithering that sort of thing

**Comment by DanielnetoDotCom** [comment]
I can see some pixels, I fell like it was better before. but looks like you are understanding this much better then me now.

We use to use this code: 

`$ffmpeg ="ffmpeg -ss {$duration} -t {$howLong} -i {$pathFileName} -i {$pathFileName}palette.png -filter_complex \"fps=10,scale=320:-1:flags=lanczos[x];[x][1:v]paletteuse\" {$destinationFile}"`


but if your code fixes the portrait gif, that is fine, the aspect ratio is more important then the colors

**Comment by OhioVR** [comment]
Ok sorry I couldn't be much more help. BTW I was wondering since we can't incorporate ffmpeg into the youphptube streamer code would it be possible with php to grab the first frame from the animated gif for the thumb? That way the aspect would be preserved and we wouldn't have to delve to much into difficult php imaging to pull it off. Or another way to have portrait thumbs without ffmpeg on the streamer is to send composed thumbs from the encoder. But I was thinking grabbing the first frame from a gif might be easier.

**Comment by DanielnetoDotCom** [comment]
I am trying to avoid ffmpeg on streamer.

I want the streamer to be able to be installed in any shared host. ffmpeg requires root access

**Comment by OhioVR** [comment]
That is how I understand the problem yes. But is there any image conversion utility already built into the streamer as it is now? A simple gif to jpeg conversion might be good enough if it is even possible without ffmpeg. I figure somehow it can create images. Not a distant step to convert them.

**Comment by DanielnetoDotCom** [comment]
Yes there is https://github.com/DanielnetoDotCom/YouPHPTube/blob/866e80f3c0c63ea192de7c594f1b29e614f448ee/objects/functions.php#L878

**Pull request merged**
